# Generated by Django 6.0 on 2026-08-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_curso_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
